name: sheek
description: ecommerce app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  http: ^0.13.5
  logger: ^2.0.2+1
  get_it: ^7.6.4
  flutter_localizations:
    sdk: flutter
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0
  convex_bottom_bar: ^3.2.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4
  flutter_slidable: ^3.0.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  geolocator: ^10.1.0
  video_player: ^2.7.2
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.1.2
  lottie: ^2.6.0
  connectivity_plus: ^5.0.2
  visibility_detector: ^0.4.0+2
  flutter_animate: ^4.5.0
  pin_code_fields: ^8.0.1
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.3.3
  firebase_analytics: ^10.8.0
  flutter_hsvcolor_picker: ^1.5.0




 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  
flutter:


  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/Sans/SourceSans3-Regular.ttf
        - asset: assets/fonts/Sans/SourceSans3-Bold.ttf
        - asset: assets/fonts/Sans/SourceSans3-Black.ttf
        - asset: assets/fonts/Sans/SourceSans3-Light.ttf
        - asset: assets/fonts/Sans/SourceSans3-Medium.ttf
        - asset: assets/fonts/Sans/SourceSans3-SemiBold.ttf
